doctrine_migrations:
    migrations_paths:
        'Elements\Bundle\ProcessManagerBundle\Migrations': '%kernel.project_dir%/vendor/elements/process-manager-bundle/src/Migrations'
    em: default # Use the default entity manager for migrations (important if other entity managers are defined)