doctrine_migrations:
    connection: default
    em : null #don't use an entity manager if defined, use the default connection
    migrations_paths:
        'Elements\Bundle\ProcessManagerBundle\Migrations': '%kernel.project_dir%/vendor/elements/process-manager-bundle/src/Migrations'